[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"

# Optimizer settings
optimizer = true
optimizer_runs = 200
verbosity = 2 

# Gas reports
gas_reports = ["*"]
fuzz = { runs = 256 }
# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# RPC endpoints
[rpc_endpoints]
base_sepolia = "hhttps://sepolia.base.org"
mainnet = "https://eth.llamarpc.com"